### ISSUE TITLE
Suggestion: No arguments = "list"

### ISSUE THREAD

**Issue by jbiason** [soywod/unfog#30]
Just a simple suggestion:

When you run `unfog` with no options, you get a `unfog: invalid arguments`. I suppose it could be a lot more "friendly" if instead of that, it just assumed the user want to list the current, not-done tasks.

**Comment by soywod** [comment]
It's a good point, I was also annoyed by this. I will push sth soon. Thanks for the feedback!

**Comment by soywod** [comment]
Added in the [last release](https://github.com/soywod/unfog.cli/releases/tag/v0.4.5) :tada:

**Comment by soywod** [comment]
The parser has been refactored in the v1.0.0 (based on (optparse-applicative)[https://github.com/pcapriotti/optparse-applicative#custom-parsing-and-error-handling] lib), and there is no "default" command. I will check how to put back this feature.

**Comment by soywod** [comment]
Added back in [v1.0.1](https://github.com/soywod/unfog/releases/tag/v1.0.1) :tada:
