### ISSUE TITLE
Prelude.read: no parse due time

### ISSUE THREAD

**Issue by soywod** [soywod/unfog#34]
https://github.com/soywod/unfog.vim/issues/11

Regression after upgrading ghc 8.8.4. `UTCTime` can't be read anymore without explicit timezone.

**Comment by brokenax3** [comment]
I've only just started using unfog this semester. It seems to help to tell me how much time I've spent on each task at hand. I do feel like the due date/ time feature is pretty helpful to get a gauge on the time remaining to the end of the deadline. 

It is a useful plugin to integrate into my vim workflow. Thanks again! Appreciate the prompt reply.

**Comment by soywod** [comment]
Thanks for the feedback, I will take it into consideration. I will let you know when the `v1` is ready (including the fix for this bug). I'm glad it helps you too. I'm using it since almost a year and it really improved my accuracy. If you have any suggestion, feel free to propose!

**Comment by soywod** [comment]
Bug fixed in https://github.com/soywod/unfog/releases/tag/v1.0.0. The vim plugin will be adapted soon, to match the new v1.0.0 API.
