### ISSUE TITLE
Store file location?

### ISSUE THREAD

**Issue by kristijanhusak** [soywod/unfog#40]
Hi,

is it possible to change location of the store file?
I would like to keep it in `~/Dropbox` folder so it is synced across all my systems.

**Comment by soywod** [comment]
I was thinking about introducing a config file. It's a good occasion! I will try sth and let you know.

**Comment by soywod** [comment]
I have a working model in an other project, I will integrate it soon. The config file will be at TOML format.

**Comment by soywod** [comment]
Added in [v1.0.2](https://github.com/soywod/unfog/releases/tag/v1.0.2) :tada:

**Comment by soywod** [comment]
README updated https://github.com/soywod/unfog#configuration.
