### ISSUE TITLE
List PROJECT column when using `unfog worktime`

### ISSUE THREAD

**Issue by razcore-rad** [soywod/unfog#56]
Since `unfog worktime` uses the PROJECT as key and not IDs or DESCriptions it should output the PROJECT column when listing the content so we don't have to go back and forth between `unfog worktime` and `unfog list`. Thanks!

**Comment by soywod** [comment]
I have no free time to allocate to this project unfortunately :disappointed: I let you know whenever I can do sth. Or feel free to propose a PR :slightly_smiling_face:
